extends: [airbnb, prettier]
plugins: [prettier]
rules:
  # prettier/prettier: [error]
  react/function-component-definition: off
  react/jsx-filename-extension: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  import/prefer-default-export: off
env:
  browser: true
